// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MauiDemo.Model;
//
//    var studentreq = Studentreq.FromJson(jsonString);

namespace MauiDemo.Model
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Studentreq
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("password")]
        public string Password { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("profile_image")]
        public Uri ProfileImage { get; set; }

        [JsonProperty("profile")]
        public Profile Profile { get; set; }

        [JsonProperty("current_term_courses")]
        public List<string> CurrentTermCourses { get; set; }

        [JsonProperty("previous_term_courses")]
        public List<List<string>> PreviousTermCourses { get; set; }

        [JsonProperty("registeredCourses")]
        public List<RegisteredCourse> RegisteredCourses { get; set; }
    }

    public partial class Profile
    {
        [JsonProperty("student_id")]
        public string StudentId { get; set; }

        [JsonProperty("faculty")]
        public string Faculty { get; set; }

        [JsonProperty("department")]
        public string Department { get; set; }
    }

    public partial class RegisteredCourse
    {
        [JsonProperty("courseId")]
        public string CourseId { get; set; }

        [JsonProperty("courseName")]
        public string CourseName { get; set; }

        [JsonProperty("semester")]
        public string Semester { get; set; }
    }

    public partial class Studentreq
    {
        public static Studentreq FromJson(string json) => JsonConvert.DeserializeObject<Studentreq>(json, MauiDemo.Model.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Studentreq self) => JsonConvert.SerializeObject(self, MauiDemo.Model.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
